# Puerto diferente para no chocar con ms-pets
server.port=8083
# Cambia 'mail.sendgrid.key' por 'sendgrid.api.key'
sendgrid.api.key=${SENDGRID_API_KEY}
sendgrid.from.email=${SENDGRID_FROM_EMAIL}
sendgrid.template.id=d-4a42f61062d84d81a0f8d7fb171c7813