spring.application.name=ms-users
server.port=8081

# Conexión dinámica usando las variables del .env
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# En local será esto
bff.cors.allowed-origins=http://localhost:3000, https://sanosysalvos-five.vercel.app
# Cuando estés en AWS, no tocas este archivo, sino que inyectas 
# una variable de entorno llamada BFF_CORS_ALLOWED_ORIGINS
# Seguridad - Firebase/Google OAuth2
# Nota: Asegúrate de que el issuer-uri sea el correcto de tu proyecto Firebase
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/sanos-y-salvos-git
